### ISSUE TITLE
Error creating Evernote file from md files

### ISSUE THREAD

**Issue by prebencarlsen** [karloskalcium/md2enex#4]

**Comment by prebencarlsen** [comment]
Hi, 

I'm getting this error when trying to convert md files from Obsidian to the Evernote format.

Any help is welcome

```
❯ ./md2enex.py -d /Users/carlsen/Desktop/md_source/ -o /Users/carlsen/Desktop/md_output/
Traceback (most recent call last):
  File "/Users/carlsen/md2enex/./md2enex.py", line 221, in <module>
    main(args.directory, args.output)
  File "/Users/carlsen/md2enex/./md2enex.py", line 209, in main
    write_enex(target_directory, output_filename)
  File "/Users/carlsen/md2enex/./md2enex.py", line 192, in write_enex
    tree.write(output_file, encoding="UTF-8", method='xml', pretty_print=True,
  File "src/lxml/etree.pyx", line 2075, in lxml.etree._ElementTree.write
  File "src/lxml/serializer.pxi", line 747, in lxml.etree._tofilelike
  File "src/lxml/serializer.pxi", line 815, in lxml.etree._create_output_buffer
  File "src/lxml/serializer.pxi", line 805, in lxml.etree._create_output_buffer
IsADirectoryError: [Errno 21] Is a directory
```

**Comment by karlbrown-va** [comment]
@prebencarlsen the `-o` parameter should be a filename, not a directory, as the output is a single .enex file.

**Comment by karloskalcium** [comment]
[@prebencarlsen](https://github.com/prebencarlsen) the -o parameter should be a filename, not a directory, as the output is a single .enex file.
